### ISSUE TITLE
vegas in Contao 4.9

### ISSUE THREAD

**Issue by tonsinn** [jonnysp/Vegas#1]
Welche Voraussetzungen müssen erfüllt sein, damit der Vegas-Slider im Frontend sichtbar ist?
Im Artikel habe ich das Element "Vegas 2" mit zwei Slides eingebaut, aber im Quellcode ist nur zu sehen:
[vegas-html.txt](https://github.com/jonnysp/Vegas/files/4688092/vegas-html.txt)
Was fehlt hier?

**Comment by jonnysp** [comment]
Hallo Mathias,

danke für deine Anfrage.

damit der slider sichtbar ist must du es einem content element oder artikel eine klasse oder id vergeben 
![grafik](https://user-images.githubusercontent.com/1651241/83012116-432ff900-a01b-11ea-837a-107907e40f93.png)


und dann in ELEMENT zuordnung richtig vergeben.
![grafik](https://user-images.githubusercontent.com/1651241/83011892-f0eed800-a01a-11ea-8dd6-7363fd39c750.png)
dieses element sollte auch einen content oder gewisse größe haben damit der hintergrund angezeigt wird.

viele grüße Jonny

**Comment by tonsinn** [comment]
Danke ... na klar - logisch.
Kaum macht man's richtig, schon geht's.

**Comment by jonnysp** [comment]
Was mich aber noch stört sind die werte mit den ausrufezeichen...

**"preload":!0,"timer":!1,"autoplay":!0**

sollte eigentlich so aussehen.

**"preload":false,"timer":true,"autoplay":false**

wenns aber geht nicht weiter darübernachdenken :-)
